### ISSUE TITLE
Make instructions universal

### ISSUE THREAD

**Issue by sgspectra** [sgspectra/suicide#11]
Increase game awareness by making the instructions appear on every client, not just the clients directly involved

**Comment by milesoldenburg** [comment]
If current player X gets to give out N drinks:
1. Instruction should say, 'X gets to give out N drinks'
2. After popup is finished, instructions should say each player that was given drinks and the amount

**Comment by sgspectra** [comment]
This could be done by adding an instruction variable to the shared state.
